version: 2

before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip


dockers_v2:
  - id: mithra
    sbom: false
    platforms:
      - linux/amd64
    images:
      - ghcr.io/fmotalleb/mithra
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - latest
    labels:
      "org.opencontainers.image.description": "Mithra (IP Scanner)"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    ids:
      - default

release:
  github:
    name: mithra
    owner: fmotalleb
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
